"""Add profile_image and is_active to Doctor

Revision ID: 9c570ecd6477
Revises: aa024d679301
Create Date: 2026-05-19 23:24:19.823968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c570ecd6477'
down_revision = 'aa024d679301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=False, server_default='default_doctor.jpg'))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
