"""Add bio field to Doctor model

Revision ID: aa024d679301
Revises: 3167d36bc93c
Create Date: 2026-05-19 20:57:51.740230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa024d679301'
down_revision = '3167d36bc93c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        # Remove the unique constraint line if it's already there or give it a name
        # batch_op.create_unique_constraint('uq_doctor_user_id', ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        # batch_op.drop_constraint('uq_doctor_user_id', type_='unique')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
